export const awards = {
  awards_claim_award_info_message: 'You received a {{awardTitle}} award!',
  awards_claim_see_award_options_button_text: 'See award options',
  awards_claim_award_error_message: 'There was an error claiming this award. Please try again.',
  awards_claim_award_success_message: 'Your award has been claimed',
  awards_claim_award_button_text: 'Claim Award',
  awards_award_sent_by_text: 'Sent by',
  awards_award_reason_text: 'Reason for Award',
  awards_award_date_received: 'Date: {{date}}',
  awards_award_view_award_button_text: 'View Award',
  awards_congratulations_text: 'Congratulations!',
  awards_load_more_awards_button_text: 'Load more',
  awards_load_more_awards_button_title: 'Load more awards',
  awards_approval_reason: 'Approval Reason',
  awards_approval_reason_plural: 'Approval Reasons',
  awards_approval_approver_reason: `{{approverName}}'s reason`,
  awards_claim_award_worth_value_message:
      'This is worth <strong>{{awardValue}}</strong> and you can spend the amount instantly or let it build up in your account.',
  awards_recepient_award_info_message:
      '{{recepient}} received {{article}} <strong>{{awardTitle}}</strong> from <strong>{{firstName}} {{lastName}}</strong>',
  awards_recepients_list: 'Users who received this {{award}}',
  awards_claim_award_trophy_aria_label: 'Trophy',
  awards_print_search_recipient_label: 'Search for recipient',
  awards_print_start_date_label: 'Period start date',
  awards_print_group_label: 'Group',
  awards_print_end_date_label: 'Period end date',
  awards_print_select_award_aria_label: 'Select award',
  awards_print_selected_link_text: 'Print selected',
  awards_print_select_visible_link_text: 'Select visible',
  awards_print_select_all_link_text: 'Select all {{count}}',
  awards_print_select_deselect_link_text: 'Deselect',
  awards_print_show_search_options_link_text: 'Show search options',
  awards_print_hide_search_options_link_text: 'Hide search options',
  awards_print_filters_sort_by_link_text: 'Sort by:',
  awards_print_selected_awards_count: '{{count}} selected',
  awards_print_filters_sort_by_newest_text: 'Newest first',
  awards_print_filters_sort_by_oldest_text: 'Oldest first',
  awards_print_radio_feed_view_label: 'Feed view',
  awards_print_radio_certificate_label: 'Certificate',
  awards_print_recognition_title: 'Print recognition',
  awards_print_recognition_table_date: 'Date',
  awards_print_recognition_table_recipient: 'Recipient',
  awards_print_recognition_table_award_name: 'Award name',
  awards_print_recognition_table_award_value: 'Award value',
  awards_print_recognition_table_sender: 'Sender',
  awards_print_recognition_table_actions: 'Actions',
  awards_recognition_recipients_default_one:
      '<strong>{{recipientOne}}</strong> received {{recognitionName, article}} <strong>"{{recognitionName}}"</strong> from <strong>{{sender}}</strong>',
  awards_recognition_recipients_default_two:
      '<strong>{{recipientOne}}</strong> and <strong>{{recipientTwo}}</strong> received {{recognitionName, article}} <strong>"{{recognitionName}}"</strong> from <strong>{{sender}}</strong>',
  awards_recognition_recipients_default_three:
      '<strong>{{recipientOne}}</strong>, <strong>{{recipientTwo}}</strong> and <strong>{{recipientThree}}</strong> received {{recognitionName, article}} <strong>"{{recognitionName}}"</strong> from <strong>{{sender}}</strong>',
  awards_recognition_recipients_default_more_than_three:
      '<strong>{{recipientOne}}</strong> and <strong>{{recipientTwo}}</strong> and {{remainingRecipientsCount}} others received {{recognitionName, article}} <strong>"{{recognitionName}}"</strong> from <strong>{{sender}}</strong>',
  awards_recognition_recipients_nomination_one:
      '<strong>{{recipientOne}}</strong> has been nominated for <strong>"{{recognitionName}}"</strong> from <strong>{{sender}}</strong>',
  awards_recognition_recipients_nomination_two:
      '<strong>{{recipientOne}}</strong> and <strong>{{recipientTwo}}</strong> have been nomiprueba{{remainingRecipientsCount}} others have been nominated for <strong>"{{recognitionName}}"</strong> from <strong>{{sender}}</strong>',
  awards_list_end_of_list_button_text: 'End of list',
  awards_message_return_to_srw: 'Return To Social Recognition Wall',
  awards_activity_date: 'Date: {{date}}',
  awards_activity_points_for_last_month_message: 'Check your activity points for the last 30 days.',
  awards_comment_button: 'Comment',
  awards_comment_button_plural: 'Comments',
  awards_award_sent_by_text1: 'Sent by',
  launch_meter_title1: 'Launch meter',
  launch_meter_need_help1: 'Need help?',
}
